apiVersion: pipelines.azuredevops.m.crossplane.io/v1alpha1
kind: VariableGroup
metadata:
  annotations:
    meta.upbound.io/example-id: pipelines/v1alpha1/variablegroup
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    allowAccess: true
    description: Example Variable Group Description
    name: Example Variable Group
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    variable:
    - name: key1
      value: val1
    - isSecret: true
      name: key2
      secretValueSecretRef:
        key: example-key
        name: example-secret

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: pipelines/v1alpha1/variablegroup
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
