apiVersion: repos.azuredevops.crossplane.io/v1alpha1
kind: GitRepositoryBranch
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/gitrepositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-branch-name
    refBranchSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    repositoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: repos.azuredevops.crossplane.io/v1alpha1
kind: GitRepository
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/gitrepositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Git Repository
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/gitrepositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
