apiVersion: security.azuredevops.m.crossplane.io/v1alpha1
kind: WorkitemqueryPermissions
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/workitemquerypermissions
  labels:
    testing.upbound.io/example-name: project-wiq-root-permissions
  name: project-wiq-root-permissions
  namespace: upbound-system
spec:
  forProvider:
    permissions:
      CreateRepository: Deny
      DeleteRepository: Deny
      RenameRepository: NotSet
    principal: ${data.azuredevops_group.example-readers.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/workitemquerypermissions
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
