apiVersion: security.azuredevops.m.crossplane.io/v1alpha1
kind: ServicehookPermissions
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/servicehookpermissions
  labels:
    testing.upbound.io/example-name: example-permissions
  name: example-permissions
  namespace: upbound-system
spec:
  forProvider:
    permissions:
      DeleteSubscriptions: allow
      EditSubscriptions: allow
      PublishEvents: allow
      ViewSubscriptions: allow
    principal: ${data.azuredevops_group.example-readers.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/servicehookpermissions
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
