apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Workitem
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/workitem
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: azuredevops_project
    state: Active
    tags:
    - Tag
    title: Example Work Item
    type: Issue

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/workitem
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
