apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: ServiceendpointSSH
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointssh
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    host: 1.2.3.4
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceEndpointName: Example SSH
    username: username

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointssh
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
