apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: ServiceendpointGitlab
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointgitlab
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    apiTokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    description: Managed by Terraform
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceEndpointName: Example GitLab
    url: https://gitlab.com
    username: username

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointgitlab
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
