apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: ServiceendpointCheckmarxOne
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointcheckmarxone
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    apiKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverUrl: https://server.com
    serviceEndpointName: Example Checkmarx One

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointcheckmarxone
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
