// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AreaPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BuildDefinitionPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BuildFolderPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FeedPermission) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GitPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupEntitlement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupMembership) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IterationPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LibraryPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PipelineAuthorization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ResourceAuthorization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecurityroleAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceendpointPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServicehookPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServicePrincipalEntitlement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TaggingPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Team) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamAdministrators) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamMembers) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserEntitlement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VariableGroupPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkitemqueryPermissions) Hub() {}
