// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type VariableGroupPermissionsInitParameters struct {

	// the permissions to assign. The following permissions are available.
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The group principal to assign the permissions.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// Replace (true) or merge (false) the permissions. Default: true
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// The id of the variable group to assign the permissions.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/pipelines/v1alpha1.VariableGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	VariableGroupID *string `json:"variableGroupId,omitempty" tf:"variable_group_id,omitempty"`

	// Reference to a VariableGroup in pipelines to populate variableGroupId.
	// +kubebuilder:validation:Optional
	VariableGroupIDRef *v1.NamespacedReference `json:"variableGroupIdRef,omitempty" tf:"-"`

	// Selector for a VariableGroup in pipelines to populate variableGroupId.
	// +kubebuilder:validation:Optional
	VariableGroupIDSelector *v1.NamespacedSelector `json:"variableGroupIdSelector,omitempty" tf:"-"`
}

type VariableGroupPermissionsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// the permissions to assign. The following permissions are available.
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The group principal to assign the permissions.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Replace (true) or merge (false) the permissions. Default: true
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// The id of the variable group to assign the permissions.
	VariableGroupID *string `json:"variableGroupId,omitempty" tf:"variable_group_id,omitempty"`
}

type VariableGroupPermissionsParameters struct {

	// the permissions to assign. The following permissions are available.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The group principal to assign the permissions.
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// Replace (true) or merge (false) the permissions. Default: true
	// +kubebuilder:validation:Optional
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// The id of the variable group to assign the permissions.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/pipelines/v1alpha1.VariableGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	VariableGroupID *string `json:"variableGroupId,omitempty" tf:"variable_group_id,omitempty"`

	// Reference to a VariableGroup in pipelines to populate variableGroupId.
	// +kubebuilder:validation:Optional
	VariableGroupIDRef *v1.NamespacedReference `json:"variableGroupIdRef,omitempty" tf:"-"`

	// Selector for a VariableGroup in pipelines to populate variableGroupId.
	// +kubebuilder:validation:Optional
	VariableGroupIDSelector *v1.NamespacedSelector `json:"variableGroupIdSelector,omitempty" tf:"-"`
}

// VariableGroupPermissionsSpec defines the desired state of VariableGroupPermissions
type VariableGroupPermissionsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VariableGroupPermissionsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VariableGroupPermissionsInitParameters `json:"initProvider,omitempty"`
}

// VariableGroupPermissionsStatus defines the observed state of VariableGroupPermissions.
type VariableGroupPermissionsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VariableGroupPermissionsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VariableGroupPermissions is the Schema for the VariableGroupPermissionss API. Manages permissions for aa Azure DevOps Variable Group
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type VariableGroupPermissions struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.principal) || (has(self.initProvider) && has(self.initProvider.principal))",message="spec.forProvider.principal is a required parameter"
	Spec   VariableGroupPermissionsSpec   `json:"spec"`
	Status VariableGroupPermissionsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VariableGroupPermissionsList contains a list of VariableGroupPermissionss
type VariableGroupPermissionsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VariableGroupPermissions `json:"items"`
}

// Repository type metadata.
var (
	VariableGroupPermissions_Kind             = "VariableGroupPermissions"
	VariableGroupPermissions_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VariableGroupPermissions_Kind}.String()
	VariableGroupPermissions_KindAPIVersion   = VariableGroupPermissions_Kind + "." + CRDGroupVersion.String()
	VariableGroupPermissions_GroupVersionKind = CRDGroupVersion.WithKind(VariableGroupPermissions_Kind)
)

func init() {
	SchemeBuilder.Register(&VariableGroupPermissions{}, &VariableGroupPermissionsList{})
}
