// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type GitRepositoryBranchInitParameters struct {

	// The name of the branch in short format not prefixed with refs/heads/.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The reference to the source branch to create the branch from, in <name> or refs/heads/<name> format. Conflict with ref_tag, ref_commit_id.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/repos/v1alpha1.GitRepository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("default_branch",false)
	RefBranch *string `json:"refBranch,omitempty" tf:"ref_branch,omitempty"`

	// Reference to a GitRepository in repos to populate refBranch.
	// +kubebuilder:validation:Optional
	RefBranchRef *v1.Reference `json:"refBranchRef,omitempty" tf:"-"`

	// Selector for a GitRepository in repos to populate refBranch.
	// +kubebuilder:validation:Optional
	RefBranchSelector *v1.Selector `json:"refBranchSelector,omitempty" tf:"-"`

	// The commit object ID to create the branch from. Conflict with ref_branch, ref_tag.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/repos/v1alpha1.GitRepositoryBranch
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("last_commit_id",true)
	RefCommitID *string `json:"refCommitId,omitempty" tf:"ref_commit_id,omitempty"`

	// Reference to a GitRepositoryBranch in repos to populate refCommitId.
	// +kubebuilder:validation:Optional
	RefCommitIDRef *v1.Reference `json:"refCommitIdRef,omitempty" tf:"-"`

	// Selector for a GitRepositoryBranch in repos to populate refCommitId.
	// +kubebuilder:validation:Optional
	RefCommitIDSelector *v1.Selector `json:"refCommitIdSelector,omitempty" tf:"-"`

	// The reference to the tag to create the branch from, in <name> or refs/tags/<name> format. Conflict with ref_branch, ref_commit_id.
	RefTag *string `json:"refTag,omitempty" tf:"ref_tag,omitempty"`

	// The ID of the repository the branch is created against.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/repos/v1alpha1.GitRepository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a GitRepository in repos to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v1.Reference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a GitRepository in repos to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v1.Selector `json:"repositoryIdSelector,omitempty" tf:"-"`
}

type GitRepositoryBranchObservation struct {

	// The ID of the Git Repository Branch, in the format <repository_id>:<name>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The commit object ID of last commit on the branch.
	LastCommitID *string `json:"lastCommitId,omitempty" tf:"last_commit_id,omitempty"`

	// The name of the branch in short format not prefixed with refs/heads/.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The reference to the source branch to create the branch from, in <name> or refs/heads/<name> format. Conflict with ref_tag, ref_commit_id.
	RefBranch *string `json:"refBranch,omitempty" tf:"ref_branch,omitempty"`

	// The commit object ID to create the branch from. Conflict with ref_branch, ref_tag.
	RefCommitID *string `json:"refCommitId,omitempty" tf:"ref_commit_id,omitempty"`

	// The reference to the tag to create the branch from, in <name> or refs/tags/<name> format. Conflict with ref_branch, ref_commit_id.
	RefTag *string `json:"refTag,omitempty" tf:"ref_tag,omitempty"`

	// The ID of the repository the branch is created against.
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`
}

type GitRepositoryBranchParameters struct {

	// The name of the branch in short format not prefixed with refs/heads/.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The reference to the source branch to create the branch from, in <name> or refs/heads/<name> format. Conflict with ref_tag, ref_commit_id.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/repos/v1alpha1.GitRepository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("default_branch",false)
	// +kubebuilder:validation:Optional
	RefBranch *string `json:"refBranch,omitempty" tf:"ref_branch,omitempty"`

	// Reference to a GitRepository in repos to populate refBranch.
	// +kubebuilder:validation:Optional
	RefBranchRef *v1.Reference `json:"refBranchRef,omitempty" tf:"-"`

	// Selector for a GitRepository in repos to populate refBranch.
	// +kubebuilder:validation:Optional
	RefBranchSelector *v1.Selector `json:"refBranchSelector,omitempty" tf:"-"`

	// The commit object ID to create the branch from. Conflict with ref_branch, ref_tag.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/repos/v1alpha1.GitRepositoryBranch
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("last_commit_id",true)
	// +kubebuilder:validation:Optional
	RefCommitID *string `json:"refCommitId,omitempty" tf:"ref_commit_id,omitempty"`

	// Reference to a GitRepositoryBranch in repos to populate refCommitId.
	// +kubebuilder:validation:Optional
	RefCommitIDRef *v1.Reference `json:"refCommitIdRef,omitempty" tf:"-"`

	// Selector for a GitRepositoryBranch in repos to populate refCommitId.
	// +kubebuilder:validation:Optional
	RefCommitIDSelector *v1.Selector `json:"refCommitIdSelector,omitempty" tf:"-"`

	// The reference to the tag to create the branch from, in <name> or refs/tags/<name> format. Conflict with ref_branch, ref_commit_id.
	// +kubebuilder:validation:Optional
	RefTag *string `json:"refTag,omitempty" tf:"ref_tag,omitempty"`

	// The ID of the repository the branch is created against.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/repos/v1alpha1.GitRepository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	RepositoryID *string `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a GitRepository in repos to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v1.Reference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a GitRepository in repos to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v1.Selector `json:"repositoryIdSelector,omitempty" tf:"-"`
}

// GitRepositoryBranchSpec defines the desired state of GitRepositoryBranch
type GitRepositoryBranchSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GitRepositoryBranchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GitRepositoryBranchInitParameters `json:"initProvider,omitempty"`
}

// GitRepositoryBranchStatus defines the observed state of GitRepositoryBranch.
type GitRepositoryBranchStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GitRepositoryBranchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GitRepositoryBranch is the Schema for the GitRepositoryBranchs API. Manages a Git Repository Branch.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type GitRepositoryBranch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   GitRepositoryBranchSpec   `json:"spec"`
	Status GitRepositoryBranchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GitRepositoryBranchList contains a list of GitRepositoryBranchs
type GitRepositoryBranchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GitRepositoryBranch `json:"items"`
}

// Repository type metadata.
var (
	GitRepositoryBranch_Kind             = "GitRepositoryBranch"
	GitRepositoryBranch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GitRepositoryBranch_Kind}.String()
	GitRepositoryBranch_KindAPIVersion   = GitRepositoryBranch_Kind + "." + CRDGroupVersion.String()
	GitRepositoryBranch_GroupVersionKind = CRDGroupVersion.WithKind(GitRepositoryBranch_Kind)
)

func init() {
	SchemeBuilder.Register(&GitRepositoryBranch{}, &GitRepositoryBranchList{})
}
