// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *BranchPolicyAutoReviewers) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BranchPolicyBuildValidation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BranchPolicyCommentResolution) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BranchPolicyMergeTypes) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BranchPolicyMinReviewers) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BranchPolicyStatusCheck) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BranchPolicyWorkItemLinking) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CheckApproval) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CheckBranchControl) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CheckBusinessHours) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CheckExclusiveLock) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CheckRequiredTemplate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CheckRestAPI) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GitRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GitRepositoryBranch) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GitRepositoryFile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryPolicyAuthorEmailPattern) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryPolicyCaseEnforcement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryPolicyCheckCredentials) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryPolicyFilePathPattern) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryPolicyMaxFileSize) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryPolicyMaxPathLength) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryPolicyReservedNames) Hub() {}
