// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package cluster

import (
	"github.com/glalanne/provider-azuredevops/config/cluster/agent_pool"
	"github.com/glalanne/provider-azuredevops/config/cluster/agent_queue"
	"github.com/glalanne/provider-azuredevops/config/cluster/area_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/branch_policy_auto_reviewers"
	"github.com/glalanne/provider-azuredevops/config/cluster/branch_policy_build_validation"
	"github.com/glalanne/provider-azuredevops/config/cluster/branch_policy_comment_resolution"
	"github.com/glalanne/provider-azuredevops/config/cluster/branch_policy_merge_types"
	"github.com/glalanne/provider-azuredevops/config/cluster/branch_policy_min_reviewers"
	"github.com/glalanne/provider-azuredevops/config/cluster/branch_policy_status_check"
	"github.com/glalanne/provider-azuredevops/config/cluster/branch_policy_work_item_linking"
	"github.com/glalanne/provider-azuredevops/config/cluster/build_definition"
	"github.com/glalanne/provider-azuredevops/config/cluster/build_definition_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/build_folder"
	"github.com/glalanne/provider-azuredevops/config/cluster/build_folder_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/check_approval"
	"github.com/glalanne/provider-azuredevops/config/cluster/check_branch_control"
	"github.com/glalanne/provider-azuredevops/config/cluster/check_business_hours"
	"github.com/glalanne/provider-azuredevops/config/cluster/check_exclusive_lock"
	"github.com/glalanne/provider-azuredevops/config/cluster/check_required_template"
	"github.com/glalanne/provider-azuredevops/config/cluster/check_rest_api"
	"github.com/glalanne/provider-azuredevops/config/cluster/dashboard"
	"github.com/glalanne/provider-azuredevops/config/cluster/elastic_pool"
	"github.com/glalanne/provider-azuredevops/config/cluster/environment"
	"github.com/glalanne/provider-azuredevops/config/cluster/environment_kubernetes_resource"
	"github.com/glalanne/provider-azuredevops/config/cluster/extension"
	"github.com/glalanne/provider-azuredevops/config/cluster/feed"
	"github.com/glalanne/provider-azuredevops/config/cluster/feed_permission"
	"github.com/glalanne/provider-azuredevops/config/cluster/feed_retention_policy"
	"github.com/glalanne/provider-azuredevops/config/cluster/git_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/git_repository"
	"github.com/glalanne/provider-azuredevops/config/cluster/git_repository_branch"
	"github.com/glalanne/provider-azuredevops/config/cluster/git_repository_file"
	"github.com/glalanne/provider-azuredevops/config/cluster/group"
	"github.com/glalanne/provider-azuredevops/config/cluster/group_entitlement"
	"github.com/glalanne/provider-azuredevops/config/cluster/group_membership"
	"github.com/glalanne/provider-azuredevops/config/cluster/iteration_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/library_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/pipeline_authorization"
	"github.com/glalanne/provider-azuredevops/config/cluster/project"
	"github.com/glalanne/provider-azuredevops/config/cluster/project_features"
	"github.com/glalanne/provider-azuredevops/config/cluster/project_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/project_pipeline_settings"
	"github.com/glalanne/provider-azuredevops/config/cluster/project_tags"
	"github.com/glalanne/provider-azuredevops/config/cluster/repository_policy_author_email_pattern"
	"github.com/glalanne/provider-azuredevops/config/cluster/repository_policy_case_enforcement"
	"github.com/glalanne/provider-azuredevops/config/cluster/repository_policy_check_credentials"
	"github.com/glalanne/provider-azuredevops/config/cluster/repository_policy_file_path_pattern"
	"github.com/glalanne/provider-azuredevops/config/cluster/repository_policy_max_file_size"
	"github.com/glalanne/provider-azuredevops/config/cluster/repository_policy_max_path_length"
	"github.com/glalanne/provider-azuredevops/config/cluster/repository_policy_reserved_names"
	"github.com/glalanne/provider-azuredevops/config/cluster/resource_authorization"
	"github.com/glalanne/provider-azuredevops/config/cluster/securityrole_assignment"
	"github.com/glalanne/provider-azuredevops/config/cluster/service_principal_entitlement"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_argocd"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_artifactory"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_aws"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_azure_service_bus"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_azurecr"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_azuredevops"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_azurerm"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_bitbucket"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_black_duck"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_checkmarx_one"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_checkmarx_sast"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_checkmarx_sca"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_dockerregistry"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_dynamics_lifecycle_services"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_externaltfs"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_gcp_terraform"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_generic"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_generic_git"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_github"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_github_enterprise"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_gitlab"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_incomingwebhook"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_jenkins"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_jfrog_artifactory_v2"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_jfrog_distribution_v2"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_jfrog_platform_v2"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_jfrog_xray_v2"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_kubernetes"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_maven"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_nexus"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_npm"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_nuget"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_octopusdeploy"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_openshift"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_runpipeline"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_servicefabric"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_snyk"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_sonarcloud"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_sonarqube"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_ssh"
	"github.com/glalanne/provider-azuredevops/config/cluster/serviceendpoint_visualstudiomarketplace"
	"github.com/glalanne/provider-azuredevops/config/cluster/servicehook_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/servicehook_storage_queue_pipelines"
	"github.com/glalanne/provider-azuredevops/config/cluster/tagging_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/team"
	"github.com/glalanne/provider-azuredevops/config/cluster/team_administrators"
	"github.com/glalanne/provider-azuredevops/config/cluster/team_members"
	"github.com/glalanne/provider-azuredevops/config/cluster/user_entitlement"
	"github.com/glalanne/provider-azuredevops/config/cluster/variable_group"
	"github.com/glalanne/provider-azuredevops/config/cluster/variable_group_permissions"
	"github.com/glalanne/provider-azuredevops/config/cluster/wiki"
	"github.com/glalanne/provider-azuredevops/config/cluster/wiki_page"
	"github.com/glalanne/provider-azuredevops/config/cluster/workitem"
	"github.com/glalanne/provider-azuredevops/config/cluster/workitemquery_permissions"
)

func init() {
	ProviderConfiguration.AddConfig(git_repository.Configure)
	ProviderConfiguration.AddConfig(repository_policy_case_enforcement.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_gcp_terraform.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_servicefabric.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_generic_git.Configure)
	ProviderConfiguration.AddConfig(extension.Configure)
	ProviderConfiguration.AddConfig(agent_pool.Configure)
	ProviderConfiguration.AddConfig(environment.Configure)
	ProviderConfiguration.AddConfig(team.Configure)
	ProviderConfiguration.AddConfig(repository_policy_reserved_names.Configure)
	ProviderConfiguration.AddConfig(feed_retention_policy.Configure)
	ProviderConfiguration.AddConfig(branch_policy_comment_resolution.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_npm.Configure)
	ProviderConfiguration.AddConfig(check_branch_control.Configure)
	ProviderConfiguration.AddConfig(wiki_page.Configure)
	ProviderConfiguration.AddConfig(build_definition_permissions.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_bitbucket.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_artifactory.Configure)
	ProviderConfiguration.AddConfig(wiki.Configure)
	ProviderConfiguration.AddConfig(branch_policy_build_validation.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_dockerregistry.Configure)
	ProviderConfiguration.AddConfig(build_definition.Configure)
	ProviderConfiguration.AddConfig(team_administrators.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_permissions.Configure)
	ProviderConfiguration.AddConfig(branch_policy_auto_reviewers.Configure)
	ProviderConfiguration.AddConfig(check_approval.Configure)
	ProviderConfiguration.AddConfig(service_principal_entitlement.Configure)
	ProviderConfiguration.AddConfig(repository_policy_author_email_pattern.Configure)
	ProviderConfiguration.AddConfig(pipeline_authorization.Configure)
	ProviderConfiguration.AddConfig(user_entitlement.Configure)
	ProviderConfiguration.AddConfig(securityrole_assignment.Configure)
	ProviderConfiguration.AddConfig(git_permissions.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_azure_service_bus.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_azuredevops.Configure)
	ProviderConfiguration.AddConfig(git_repository_branch.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_jfrog_artifactory_v2.Configure)
	ProviderConfiguration.AddConfig(repository_policy_max_file_size.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_jfrog_xray_v2.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_checkmarx_sca.Configure)
	ProviderConfiguration.AddConfig(project_features.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_kubernetes.Configure)
	ProviderConfiguration.AddConfig(feed_permission.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_argocd.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_openshift.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_checkmarx_one.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_checkmarx_sast.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_generic.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_externaltfs.Configure)
	ProviderConfiguration.AddConfig(check_required_template.Configure)
	ProviderConfiguration.AddConfig(project_permissions.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_jfrog_platform_v2.Configure)
	ProviderConfiguration.AddConfig(branch_policy_merge_types.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_azurecr.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_jfrog_distribution_v2.Configure)
	ProviderConfiguration.AddConfig(area_permissions.Configure)
	ProviderConfiguration.AddConfig(build_folder.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_octopusdeploy.Configure)
	ProviderConfiguration.AddConfig(repository_policy_max_path_length.Configure)
	ProviderConfiguration.AddConfig(repository_policy_file_path_pattern.Configure)
	ProviderConfiguration.AddConfig(repository_policy_check_credentials.Configure)
	ProviderConfiguration.AddConfig(dashboard.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_azurerm.Configure)
	ProviderConfiguration.AddConfig(environment_kubernetes_resource.Configure)
	ProviderConfiguration.AddConfig(branch_policy_status_check.Configure)
	ProviderConfiguration.AddConfig(check_rest_api.Configure)
	ProviderConfiguration.AddConfig(variable_group_permissions.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_runpipeline.Configure)
	ProviderConfiguration.AddConfig(build_folder_permissions.Configure)
	ProviderConfiguration.AddConfig(group.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_ssh.Configure)
	ProviderConfiguration.AddConfig(check_business_hours.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_incomingwebhook.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_nexus.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_aws.Configure)
	ProviderConfiguration.AddConfig(variable_group.Configure)
	ProviderConfiguration.AddConfig(agent_queue.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_maven.Configure)
	ProviderConfiguration.AddConfig(group_membership.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_visualstudiomarketplace.Configure)
	ProviderConfiguration.AddConfig(project_pipeline_settings.Configure)
	ProviderConfiguration.AddConfig(branch_policy_work_item_linking.Configure)
	ProviderConfiguration.AddConfig(team_members.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_github.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_black_duck.Configure)
	ProviderConfiguration.AddConfig(feed.Configure)
	ProviderConfiguration.AddConfig(check_exclusive_lock.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_sonarcloud.Configure)
	ProviderConfiguration.AddConfig(git_repository_file.Configure)
	ProviderConfiguration.AddConfig(project_tags.Configure)
	ProviderConfiguration.AddConfig(tagging_permissions.Configure)
	ProviderConfiguration.AddConfig(group_entitlement.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_gitlab.Configure)
	ProviderConfiguration.AddConfig(workitem.Configure)
	ProviderConfiguration.AddConfig(workitemquery_permissions.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_nuget.Configure)
	ProviderConfiguration.AddConfig(branch_policy_min_reviewers.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_dynamics_lifecycle_services.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_jenkins.Configure)
	ProviderConfiguration.AddConfig(elastic_pool.Configure)
	ProviderConfiguration.AddConfig(servicehook_permissions.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_sonarqube.Configure)
	ProviderConfiguration.AddConfig(servicehook_storage_queue_pipelines.Configure)
	ProviderConfiguration.AddConfig(project.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_github_enterprise.Configure)
	ProviderConfiguration.AddConfig(resource_authorization.Configure)
	ProviderConfiguration.AddConfig(serviceendpoint_snyk.Configure)
	ProviderConfiguration.AddConfig(library_permissions.Configure)
	ProviderConfiguration.AddConfig(iteration_permissions.Configure)
}
