apiVersion: pipelines.azuredevops.m.crossplane.io/v1alpha1
kind: BuildDefinition
metadata:
  annotations:
    meta.upbound.io/example-id: pipelines/v1alpha1/builddefinition
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    ciTrigger:
    - useYaml: false
    name: Example Build Definition
    path: \ExampleFolder
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    repository:
    - branchNameSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      repoIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      repoType: TfsGit
      ymlPath: azure-pipelines.yml
    schedules:
    - branchFilter:
      - exclude:
        - test
        - regression
        include:
        - master
      daysToBuild:
      - Wed
      - Sun
      scheduleOnlyWithChanges: true
      startHours: 10
      startMinutes: 59
      timeZone: (UTC) Coordinated Universal Time
    variable:
    - name: PipelineVariable
      value: Go Microsoft!
    - isSecret: true
      name: PipelineSecret
      secretValueSecretRef:
        key: example-key
        name: example-secret
    variableGroupsRefs:
    - name: example

---

apiVersion: repos.azuredevops.m.crossplane.io/v1alpha1
kind: GitRepository
metadata:
  annotations:
    meta.upbound.io/example-id: pipelines/v1alpha1/builddefinition
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Repository
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: pipelines/v1alpha1/builddefinition
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile

---

apiVersion: pipelines.azuredevops.m.crossplane.io/v1alpha1
kind: VariableGroup
metadata:
  annotations:
    meta.upbound.io/example-id: pipelines/v1alpha1/builddefinition
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    allowAccess: true
    description: Managed by Terraform
    name: Example Pipeline Variables
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    variable:
    - name: FOO
      value: BAR
