apiVersion: security.azuredevops.crossplane.io/v1alpha1
kind: AreaPermissions
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/areapermissions
  labels:
    testing.upbound.io/example-name: example-root-permissions
  name: example-root-permissions
spec:
  forProvider:
    path: /
    permissions:
      CREATE_CHILDREN: Deny
      DELETE: Deny
      GENERIC_READ: Allow
      WORK_ITEM_READ: Allow
    principal: ${data.azuredevops_group.example-project-readers.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/areapermissions
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
