apiVersion: security.azuredevops.crossplane.io/v1alpha1
kind: GitPermissions
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/gitpermissions
  labels:
    testing.upbound.io/example-name: example-permissions
  name: example-permissions
spec:
  forProvider:
    permissions:
      CreateRepository: Deny
      DeleteRepository: Deny
      RenameRepository: NotSet
    principal: ${data.azuredevops_group.example-readers.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/gitpermissions
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
