// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AuthenticationBasicInitParameters struct {

	// The Password of the ArgoCD.
	// The ArgoCD password.
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The Username of the ArgoCD.
	// The ArgoCD user name.
	UsernameSecretRef v1.LocalSecretKeySelector `json:"usernameSecretRef" tf:"-"`
}

type AuthenticationBasicObservation struct {
}

type AuthenticationBasicParameters struct {

	// The Password of the ArgoCD.
	// The ArgoCD password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The Username of the ArgoCD.
	// The ArgoCD user name.
	// +kubebuilder:validation:Optional
	UsernameSecretRef v1.LocalSecretKeySelector `json:"usernameSecretRef" tf:"-"`
}

type AuthenticationTokenInitParameters struct {

	// Authentication Token generated through ArgoCD.
	// The ArgoCD access token.
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type AuthenticationTokenObservation struct {
}

type AuthenticationTokenParameters struct {

	// Authentication Token generated through ArgoCD.
	// The ArgoCD access token.
	// +kubebuilder:validation:Optional
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type ServiceendpointArgocdInitParameters struct {

	// An authentication_basic block for the ArgoCD as documented below.
	AuthenticationBasic *AuthenticationBasicInitParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block for the ArgoCD as documented below.
	AuthenticationToken *AuthenticationTokenInitParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the ArgoCD server to connect with.
	// Url for the ArgoCD Server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceendpointArgocdObservation struct {

	// An authentication_basic block for the ArgoCD as documented below.
	AuthenticationBasic *AuthenticationBasicParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block for the ArgoCD as documented below.
	AuthenticationToken *AuthenticationTokenParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the ArgoCD server to connect with.
	// Url for the ArgoCD Server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceendpointArgocdParameters struct {

	// An authentication_basic block for the ArgoCD as documented below.
	// +kubebuilder:validation:Optional
	AuthenticationBasic *AuthenticationBasicParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block for the ArgoCD as documented below.
	// +kubebuilder:validation:Optional
	AuthenticationToken *AuthenticationTokenParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the ArgoCD server to connect with.
	// Url for the ArgoCD Server
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// ServiceendpointArgocdSpec defines the desired state of ServiceendpointArgocd
type ServiceendpointArgocdSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServiceendpointArgocdParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceendpointArgocdInitParameters `json:"initProvider,omitempty"`
}

// ServiceendpointArgocdStatus defines the observed state of ServiceendpointArgocd.
type ServiceendpointArgocdStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceendpointArgocdObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceendpointArgocd is the Schema for the ServiceendpointArgocds API. Manages a ArgoCD server endpoint within Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type ServiceendpointArgocd struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   ServiceendpointArgocdSpec   `json:"spec"`
	Status ServiceendpointArgocdStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceendpointArgocdList contains a list of ServiceendpointArgocds
type ServiceendpointArgocdList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceendpointArgocd `json:"items"`
}

// Repository type metadata.
var (
	ServiceendpointArgocd_Kind             = "ServiceendpointArgocd"
	ServiceendpointArgocd_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceendpointArgocd_Kind}.String()
	ServiceendpointArgocd_KindAPIVersion   = ServiceendpointArgocd_Kind + "." + CRDGroupVersion.String()
	ServiceendpointArgocd_GroupVersionKind = CRDGroupVersion.WithKind(ServiceendpointArgocd_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceendpointArgocd{}, &ServiceendpointArgocdList{})
}
