// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ServiceendpointJfrogXrayV2AuthenticationBasicInitParameters struct {

	// The Password of the Artifactory.
	// The JFrog Artifactory password.
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The Username of the  Artifactory.
	// The JFrog Artifactory user name.
	UsernameSecretRef v1.LocalSecretKeySelector `json:"usernameSecretRef" tf:"-"`
}

type ServiceendpointJfrogXrayV2AuthenticationBasicObservation struct {
}

type ServiceendpointJfrogXrayV2AuthenticationBasicParameters struct {

	// The Password of the Artifactory.
	// The JFrog Artifactory password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The Username of the  Artifactory.
	// The JFrog Artifactory user name.
	// +kubebuilder:validation:Optional
	UsernameSecretRef v1.LocalSecretKeySelector `json:"usernameSecretRef" tf:"-"`
}

type ServiceendpointJfrogXrayV2AuthenticationTokenInitParameters struct {

	// Authentication Token generated through Artifactory.
	// The JFrog Artifactory access token.
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type ServiceendpointJfrogXrayV2AuthenticationTokenObservation struct {
}

type ServiceendpointJfrogXrayV2AuthenticationTokenParameters struct {

	// Authentication Token generated through Artifactory.
	// The JFrog Artifactory access token.
	// +kubebuilder:validation:Optional
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type ServiceendpointJfrogXrayV2InitParameters struct {

	// An authentication_basic block as documented below.
	AuthenticationBasic *ServiceendpointJfrogXrayV2AuthenticationBasicInitParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block as documented below.
	AuthenticationToken *ServiceendpointJfrogXrayV2AuthenticationTokenInitParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the Artifactory server to connect with.
	// Url for the JFrog Artifactory Server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceendpointJfrogXrayV2Observation struct {

	// An authentication_basic block as documented below.
	AuthenticationBasic *ServiceendpointJfrogXrayV2AuthenticationBasicParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block as documented below.
	AuthenticationToken *ServiceendpointJfrogXrayV2AuthenticationTokenParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the Artifactory server to connect with.
	// Url for the JFrog Artifactory Server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceendpointJfrogXrayV2Parameters struct {

	// An authentication_basic block as documented below.
	// +kubebuilder:validation:Optional
	AuthenticationBasic *ServiceendpointJfrogXrayV2AuthenticationBasicParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block as documented below.
	// +kubebuilder:validation:Optional
	AuthenticationToken *ServiceendpointJfrogXrayV2AuthenticationTokenParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the Artifactory server to connect with.
	// Url for the JFrog Artifactory Server
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// ServiceendpointJfrogXrayV2Spec defines the desired state of ServiceendpointJfrogXrayV2
type ServiceendpointJfrogXrayV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServiceendpointJfrogXrayV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceendpointJfrogXrayV2InitParameters `json:"initProvider,omitempty"`
}

// ServiceendpointJfrogXrayV2Status defines the observed state of ServiceendpointJfrogXrayV2.
type ServiceendpointJfrogXrayV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceendpointJfrogXrayV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceendpointJfrogXrayV2 is the Schema for the ServiceendpointJfrogXrayV2s API. Manages a JFrog XRay V2 service endpoint within an Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type ServiceendpointJfrogXrayV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   ServiceendpointJfrogXrayV2Spec   `json:"spec"`
	Status ServiceendpointJfrogXrayV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceendpointJfrogXrayV2List contains a list of ServiceendpointJfrogXrayV2s
type ServiceendpointJfrogXrayV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceendpointJfrogXrayV2 `json:"items"`
}

// Repository type metadata.
var (
	ServiceendpointJfrogXrayV2_Kind             = "ServiceendpointJfrogXrayV2"
	ServiceendpointJfrogXrayV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceendpointJfrogXrayV2_Kind}.String()
	ServiceendpointJfrogXrayV2_KindAPIVersion   = ServiceendpointJfrogXrayV2_Kind + "." + CRDGroupVersion.String()
	ServiceendpointJfrogXrayV2_GroupVersionKind = CRDGroupVersion.WithKind(ServiceendpointJfrogXrayV2_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceendpointJfrogXrayV2{}, &ServiceendpointJfrogXrayV2List{})
}
