// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ServiceendpointOctopusdeployInitParameters struct {

	// API key to connect to Octopus Deploy.
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Whether to ignore SSL errors when connecting to the Octopus server from the agent. Default to false.
	IgnoreSSLError *bool `json:"ignoreSslError,omitempty" tf:"ignore_ssl_error,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// Octopus Server url.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceendpointOctopusdeployObservation struct {

	// API key to connect to Octopus Deploy.
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether to ignore SSL errors when connecting to the Octopus server from the agent. Default to false.
	IgnoreSSLError *bool `json:"ignoreSslError,omitempty" tf:"ignore_ssl_error,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// Octopus Server url.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceendpointOctopusdeployParameters struct {

	// API key to connect to Octopus Deploy.
	// +kubebuilder:validation:Optional
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Whether to ignore SSL errors when connecting to the Octopus server from the agent. Default to false.
	// +kubebuilder:validation:Optional
	IgnoreSSLError *bool `json:"ignoreSslError,omitempty" tf:"ignore_ssl_error,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// Octopus Server url.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// ServiceendpointOctopusdeploySpec defines the desired state of ServiceendpointOctopusdeploy
type ServiceendpointOctopusdeploySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServiceendpointOctopusdeployParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceendpointOctopusdeployInitParameters `json:"initProvider,omitempty"`
}

// ServiceendpointOctopusdeployStatus defines the observed state of ServiceendpointOctopusdeploy.
type ServiceendpointOctopusdeployStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceendpointOctopusdeployObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceendpointOctopusdeploy is the Schema for the ServiceendpointOctopusdeploys API. Manages an Octopus Deploy service endpoint within Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type ServiceendpointOctopusdeploy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiKey) || (has(self.initProvider) && has(self.initProvider.apiKey))",message="spec.forProvider.apiKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   ServiceendpointOctopusdeploySpec   `json:"spec"`
	Status ServiceendpointOctopusdeployStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceendpointOctopusdeployList contains a list of ServiceendpointOctopusdeploys
type ServiceendpointOctopusdeployList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceendpointOctopusdeploy `json:"items"`
}

// Repository type metadata.
var (
	ServiceendpointOctopusdeploy_Kind             = "ServiceendpointOctopusdeploy"
	ServiceendpointOctopusdeploy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceendpointOctopusdeploy_Kind}.String()
	ServiceendpointOctopusdeploy_KindAPIVersion   = ServiceendpointOctopusdeploy_Kind + "." + CRDGroupVersion.String()
	ServiceendpointOctopusdeploy_GroupVersionKind = CRDGroupVersion.WithKind(ServiceendpointOctopusdeploy_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceendpointOctopusdeploy{}, &ServiceendpointOctopusdeployList{})
}
