// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ServiceendpointJfrogArtifactoryV2AuthenticationBasicInitParameters struct {

	// The Password of the Artifactory.
	// The JFrog Artifactory password.
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The Username of the Artifactory.
	// The JFrog Artifactory user name.
	UsernameSecretRef v1.LocalSecretKeySelector `json:"usernameSecretRef" tf:"-"`
}

type ServiceendpointJfrogArtifactoryV2AuthenticationBasicObservation struct {
}

type ServiceendpointJfrogArtifactoryV2AuthenticationBasicParameters struct {

	// The Password of the Artifactory.
	// The JFrog Artifactory password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The Username of the Artifactory.
	// The JFrog Artifactory user name.
	// +kubebuilder:validation:Optional
	UsernameSecretRef v1.LocalSecretKeySelector `json:"usernameSecretRef" tf:"-"`
}

type ServiceendpointJfrogArtifactoryV2AuthenticationTokenInitParameters struct {

	// Authentication Token generated through Artifactory.
	// The JFrog Artifactory access token.
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type ServiceendpointJfrogArtifactoryV2AuthenticationTokenObservation struct {
}

type ServiceendpointJfrogArtifactoryV2AuthenticationTokenParameters struct {

	// Authentication Token generated through Artifactory.
	// The JFrog Artifactory access token.
	// +kubebuilder:validation:Optional
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type ServiceendpointJfrogArtifactoryV2InitParameters struct {

	// An authentication_basic block as documented below.
	AuthenticationBasic *ServiceendpointJfrogArtifactoryV2AuthenticationBasicInitParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block as documented below.
	AuthenticationToken *ServiceendpointJfrogArtifactoryV2AuthenticationTokenInitParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the Artifactory server to connect with.
	// Url for the JFrog Artifactory Server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceendpointJfrogArtifactoryV2Observation struct {

	// An authentication_basic block as documented below.
	AuthenticationBasic *ServiceendpointJfrogArtifactoryV2AuthenticationBasicParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block as documented below.
	AuthenticationToken *ServiceendpointJfrogArtifactoryV2AuthenticationTokenParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the Artifactory server to connect with.
	// Url for the JFrog Artifactory Server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ServiceendpointJfrogArtifactoryV2Parameters struct {

	// An authentication_basic block as documented below.
	// +kubebuilder:validation:Optional
	AuthenticationBasic *ServiceendpointJfrogArtifactoryV2AuthenticationBasicParameters `json:"authenticationBasic,omitempty" tf:"authentication_basic,omitempty"`

	// An authentication_token block as documented below.
	// +kubebuilder:validation:Optional
	AuthenticationToken *ServiceendpointJfrogArtifactoryV2AuthenticationTokenParameters `json:"authenticationToken,omitempty" tf:"authentication_token,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/namespaced/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// URL of the Artifactory server to connect with.
	// Url for the JFrog Artifactory Server
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// ServiceendpointJfrogArtifactoryV2Spec defines the desired state of ServiceendpointJfrogArtifactoryV2
type ServiceendpointJfrogArtifactoryV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServiceendpointJfrogArtifactoryV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceendpointJfrogArtifactoryV2InitParameters `json:"initProvider,omitempty"`
}

// ServiceendpointJfrogArtifactoryV2Status defines the observed state of ServiceendpointJfrogArtifactoryV2.
type ServiceendpointJfrogArtifactoryV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceendpointJfrogArtifactoryV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceendpointJfrogArtifactoryV2 is the Schema for the ServiceendpointJfrogArtifactoryV2s API. Manages a JFrog Artifactory V2 service endpoint within an Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,azuredevops}
type ServiceendpointJfrogArtifactoryV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   ServiceendpointJfrogArtifactoryV2Spec   `json:"spec"`
	Status ServiceendpointJfrogArtifactoryV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceendpointJfrogArtifactoryV2List contains a list of ServiceendpointJfrogArtifactoryV2s
type ServiceendpointJfrogArtifactoryV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceendpointJfrogArtifactoryV2 `json:"items"`
}

// Repository type metadata.
var (
	ServiceendpointJfrogArtifactoryV2_Kind             = "ServiceendpointJfrogArtifactoryV2"
	ServiceendpointJfrogArtifactoryV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceendpointJfrogArtifactoryV2_Kind}.String()
	ServiceendpointJfrogArtifactoryV2_KindAPIVersion   = ServiceendpointJfrogArtifactoryV2_Kind + "." + CRDGroupVersion.String()
	ServiceendpointJfrogArtifactoryV2_GroupVersionKind = CRDGroupVersion.WithKind(ServiceendpointJfrogArtifactoryV2_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceendpointJfrogArtifactoryV2{}, &ServiceendpointJfrogArtifactoryV2List{})
}
