apiVersion: serviceendpoint.azuredevops.m.crossplane.io/v1alpha1
kind: ServiceendpointIncomingwebhook
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointincomingwebhook
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Managed by Terraform
    httpHeader: X-Hub-Signature
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretSecretRef:
      key: example-key
      name: example-secret
    serviceEndpointName: Example IncomingWebhook
    webhookName: example_webhook

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointincomingwebhook
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
