apiVersion: serviceendpoint.azuredevops.m.crossplane.io/v1alpha1
kind: ServiceendpointAzureServiceBus
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointazureservicebus
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    connectionStringSecretRef:
      key: example-key
      name: example-secret
    description: Managed by Terraform
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    queueName: queue
    serviceEndpointName: Example Azure Service Bus

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointazureservicebus
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
