apiVersion: serviceendpoint.azuredevops.m.crossplane.io/v1alpha1
kind: ServiceendpointDynamicsLifecycleServices
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointdynamicslifecycleservices
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    authorizationEndpoint: https://login.microsoftonline.com/organization
    clientId: 00000000-0000-0000-0000-000000000000
    description: Managed by Terraform
    lifecycleServicesApiEndpoint: https://lcsapi.lcs.dynamics.com
    passwordSecretRef:
      key: example-key
      name: example-secret
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceEndpointName: Example Service connection
    username: username

---

apiVersion: project.azuredevops.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointdynamicslifecycleservices
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
