//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPool) DeepCopyInto(out *AgentPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPool.
func (in *AgentPool) DeepCopy() *AgentPool {
	if in == nil {
		return nil
	}
	out := new(AgentPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolInitParameters) DeepCopyInto(out *AgentPoolInitParameters) {
	*out = *in
	if in.AutoProvision != nil {
		in, out := &in.AutoProvision, &out.AutoProvision
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PoolType != nil {
		in, out := &in.PoolType, &out.PoolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolInitParameters.
func (in *AgentPoolInitParameters) DeepCopy() *AgentPoolInitParameters {
	if in == nil {
		return nil
	}
	out := new(AgentPoolInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolList) DeepCopyInto(out *AgentPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolList.
func (in *AgentPoolList) DeepCopy() *AgentPoolList {
	if in == nil {
		return nil
	}
	out := new(AgentPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolObservation) DeepCopyInto(out *AgentPoolObservation) {
	*out = *in
	if in.AutoProvision != nil {
		in, out := &in.AutoProvision, &out.AutoProvision
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PoolType != nil {
		in, out := &in.PoolType, &out.PoolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolObservation.
func (in *AgentPoolObservation) DeepCopy() *AgentPoolObservation {
	if in == nil {
		return nil
	}
	out := new(AgentPoolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolParameters) DeepCopyInto(out *AgentPoolParameters) {
	*out = *in
	if in.AutoProvision != nil {
		in, out := &in.AutoProvision, &out.AutoProvision
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PoolType != nil {
		in, out := &in.PoolType, &out.PoolType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolParameters.
func (in *AgentPoolParameters) DeepCopy() *AgentPoolParameters {
	if in == nil {
		return nil
	}
	out := new(AgentPoolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolSpec) DeepCopyInto(out *AgentPoolSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolSpec.
func (in *AgentPoolSpec) DeepCopy() *AgentPoolSpec {
	if in == nil {
		return nil
	}
	out := new(AgentPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPoolStatus) DeepCopyInto(out *AgentPoolStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPoolStatus.
func (in *AgentPoolStatus) DeepCopy() *AgentPoolStatus {
	if in == nil {
		return nil
	}
	out := new(AgentPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentQueue) DeepCopyInto(out *AgentQueue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentQueue.
func (in *AgentQueue) DeepCopy() *AgentQueue {
	if in == nil {
		return nil
	}
	out := new(AgentQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentQueue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentQueueInitParameters) DeepCopyInto(out *AgentQueueInitParameters) {
	*out = *in
	if in.AgentPoolID != nil {
		in, out := &in.AgentPoolID, &out.AgentPoolID
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentQueueInitParameters.
func (in *AgentQueueInitParameters) DeepCopy() *AgentQueueInitParameters {
	if in == nil {
		return nil
	}
	out := new(AgentQueueInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentQueueList) DeepCopyInto(out *AgentQueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentQueue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentQueueList.
func (in *AgentQueueList) DeepCopy() *AgentQueueList {
	if in == nil {
		return nil
	}
	out := new(AgentQueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentQueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentQueueObservation) DeepCopyInto(out *AgentQueueObservation) {
	*out = *in
	if in.AgentPoolID != nil {
		in, out := &in.AgentPoolID, &out.AgentPoolID
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentQueueObservation.
func (in *AgentQueueObservation) DeepCopy() *AgentQueueObservation {
	if in == nil {
		return nil
	}
	out := new(AgentQueueObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentQueueParameters) DeepCopyInto(out *AgentQueueParameters) {
	*out = *in
	if in.AgentPoolID != nil {
		in, out := &in.AgentPoolID, &out.AgentPoolID
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentQueueParameters.
func (in *AgentQueueParameters) DeepCopy() *AgentQueueParameters {
	if in == nil {
		return nil
	}
	out := new(AgentQueueParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentQueueSpec) DeepCopyInto(out *AgentQueueSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentQueueSpec.
func (in *AgentQueueSpec) DeepCopy() *AgentQueueSpec {
	if in == nil {
		return nil
	}
	out := new(AgentQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentQueueStatus) DeepCopyInto(out *AgentQueueStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentQueueStatus.
func (in *AgentQueueStatus) DeepCopy() *AgentQueueStatus {
	if in == nil {
		return nil
	}
	out := new(AgentQueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticPool) DeepCopyInto(out *ElasticPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticPool.
func (in *ElasticPool) DeepCopy() *ElasticPool {
	if in == nil {
		return nil
	}
	out := new(ElasticPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticPoolInitParameters) DeepCopyInto(out *ElasticPoolInitParameters) {
	*out = *in
	if in.AgentInteractiveUI != nil {
		in, out := &in.AgentInteractiveUI, &out.AgentInteractiveUI
		*out = new(bool)
		**out = **in
	}
	if in.AutoProvision != nil {
		in, out := &in.AutoProvision, &out.AutoProvision
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
	if in.AzureResourceID != nil {
		in, out := &in.AzureResourceID, &out.AzureResourceID
		*out = new(string)
		**out = **in
	}
	if in.DesiredIdle != nil {
		in, out := &in.DesiredIdle, &out.DesiredIdle
		*out = new(float64)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RecycleAfterEachUse != nil {
		in, out := &in.RecycleAfterEachUse, &out.RecycleAfterEachUse
		*out = new(bool)
		**out = **in
	}
	if in.ServiceEndpointID != nil {
		in, out := &in.ServiceEndpointID, &out.ServiceEndpointID
		*out = new(string)
		**out = **in
	}
	if in.ServiceEndpointIDRef != nil {
		in, out := &in.ServiceEndpointIDRef, &out.ServiceEndpointIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceEndpointIDSelector != nil {
		in, out := &in.ServiceEndpointIDSelector, &out.ServiceEndpointIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceEndpointScope != nil {
		in, out := &in.ServiceEndpointScope, &out.ServiceEndpointScope
		*out = new(string)
		**out = **in
	}
	if in.ServiceEndpointScopeRef != nil {
		in, out := &in.ServiceEndpointScopeRef, &out.ServiceEndpointScopeRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceEndpointScopeSelector != nil {
		in, out := &in.ServiceEndpointScopeSelector, &out.ServiceEndpointScopeSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeToLiveMinutes != nil {
		in, out := &in.TimeToLiveMinutes, &out.TimeToLiveMinutes
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticPoolInitParameters.
func (in *ElasticPoolInitParameters) DeepCopy() *ElasticPoolInitParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticPoolInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticPoolList) DeepCopyInto(out *ElasticPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticPoolList.
func (in *ElasticPoolList) DeepCopy() *ElasticPoolList {
	if in == nil {
		return nil
	}
	out := new(ElasticPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticPoolObservation) DeepCopyInto(out *ElasticPoolObservation) {
	*out = *in
	if in.AgentInteractiveUI != nil {
		in, out := &in.AgentInteractiveUI, &out.AgentInteractiveUI
		*out = new(bool)
		**out = **in
	}
	if in.AutoProvision != nil {
		in, out := &in.AutoProvision, &out.AutoProvision
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
	if in.AzureResourceID != nil {
		in, out := &in.AzureResourceID, &out.AzureResourceID
		*out = new(string)
		**out = **in
	}
	if in.DesiredIdle != nil {
		in, out := &in.DesiredIdle, &out.DesiredIdle
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RecycleAfterEachUse != nil {
		in, out := &in.RecycleAfterEachUse, &out.RecycleAfterEachUse
		*out = new(bool)
		**out = **in
	}
	if in.ServiceEndpointID != nil {
		in, out := &in.ServiceEndpointID, &out.ServiceEndpointID
		*out = new(string)
		**out = **in
	}
	if in.ServiceEndpointScope != nil {
		in, out := &in.ServiceEndpointScope, &out.ServiceEndpointScope
		*out = new(string)
		**out = **in
	}
	if in.TimeToLiveMinutes != nil {
		in, out := &in.TimeToLiveMinutes, &out.TimeToLiveMinutes
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticPoolObservation.
func (in *ElasticPoolObservation) DeepCopy() *ElasticPoolObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticPoolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticPoolParameters) DeepCopyInto(out *ElasticPoolParameters) {
	*out = *in
	if in.AgentInteractiveUI != nil {
		in, out := &in.AgentInteractiveUI, &out.AgentInteractiveUI
		*out = new(bool)
		**out = **in
	}
	if in.AutoProvision != nil {
		in, out := &in.AutoProvision, &out.AutoProvision
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
	if in.AzureResourceID != nil {
		in, out := &in.AzureResourceID, &out.AzureResourceID
		*out = new(string)
		**out = **in
	}
	if in.DesiredIdle != nil {
		in, out := &in.DesiredIdle, &out.DesiredIdle
		*out = new(float64)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RecycleAfterEachUse != nil {
		in, out := &in.RecycleAfterEachUse, &out.RecycleAfterEachUse
		*out = new(bool)
		**out = **in
	}
	if in.ServiceEndpointID != nil {
		in, out := &in.ServiceEndpointID, &out.ServiceEndpointID
		*out = new(string)
		**out = **in
	}
	if in.ServiceEndpointIDRef != nil {
		in, out := &in.ServiceEndpointIDRef, &out.ServiceEndpointIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceEndpointIDSelector != nil {
		in, out := &in.ServiceEndpointIDSelector, &out.ServiceEndpointIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceEndpointScope != nil {
		in, out := &in.ServiceEndpointScope, &out.ServiceEndpointScope
		*out = new(string)
		**out = **in
	}
	if in.ServiceEndpointScopeRef != nil {
		in, out := &in.ServiceEndpointScopeRef, &out.ServiceEndpointScopeRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceEndpointScopeSelector != nil {
		in, out := &in.ServiceEndpointScopeSelector, &out.ServiceEndpointScopeSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeToLiveMinutes != nil {
		in, out := &in.TimeToLiveMinutes, &out.TimeToLiveMinutes
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticPoolParameters.
func (in *ElasticPoolParameters) DeepCopy() *ElasticPoolParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticPoolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticPoolSpec) DeepCopyInto(out *ElasticPoolSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticPoolSpec.
func (in *ElasticPoolSpec) DeepCopy() *ElasticPoolSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticPoolStatus) DeepCopyInto(out *ElasticPoolStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticPoolStatus.
func (in *ElasticPoolStatus) DeepCopy() *ElasticPoolStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticPoolStatus)
	in.DeepCopyInto(out)
	return out
}
