apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: ServiceendpointSnyk
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointsnyk
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    apiTokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    description: Managed by Terraform
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverUrl: https://snyk.io/
    serviceEndpointName: Example Snyk

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointsnyk
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
