apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: ServiceendpointNpm
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointnpm
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accessTokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    description: Managed by Terraform
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceEndpointName: Example npm
    url: https://registry.npmjs.org

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: serviceendpoint/v1alpha1/serviceendpointnpm
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
