// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ServiceendpointAwsInitParameters struct {

	// The AWS access key ID for signing programmatic requests.
	// The AWS access key ID for signing programmatic requests.
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Optional identifier for the assumed role session.
	// Optional identifier for the assumed role session.
	RoleSessionName *string `json:"roleSessionName,omitempty" tf:"role_session_name,omitempty"`

	// The Amazon Resource Name (ARN) of the role to assume.
	// The Amazon Resource Name (ARN) of the role to assume.
	RoleToAssume *string `json:"roleToAssume,omitempty" tf:"role_to_assume,omitempty"`

	// The AWS secret access key for signing programmatic requests.
	// The AWS secret access key for signing programmatic requests.
	SecretAccessKeySecretRef *v1.SecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The AWS session token for signing programmatic requests.
	// The AWS session token for signing programmatic requests.
	SessionTokenSecretRef *v1.SecretKeySelector `json:"sessionTokenSecretRef,omitempty" tf:"-"`

	// Enable this to attempt getting credentials with OIDC token from Azure Devops.
	// Enable this to attempt getting credentials with OIDC token from Azure Devops.
	UseOidc *bool `json:"useOidc,omitempty" tf:"use_oidc,omitempty"`
}

type ServiceendpointAwsObservation struct {

	// The AWS access key ID for signing programmatic requests.
	// The AWS access key ID for signing programmatic requests.
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Optional identifier for the assumed role session.
	// Optional identifier for the assumed role session.
	RoleSessionName *string `json:"roleSessionName,omitempty" tf:"role_session_name,omitempty"`

	// The Amazon Resource Name (ARN) of the role to assume.
	// The Amazon Resource Name (ARN) of the role to assume.
	RoleToAssume *string `json:"roleToAssume,omitempty" tf:"role_to_assume,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// Enable this to attempt getting credentials with OIDC token from Azure Devops.
	// Enable this to attempt getting credentials with OIDC token from Azure Devops.
	UseOidc *bool `json:"useOidc,omitempty" tf:"use_oidc,omitempty"`
}

type ServiceendpointAwsParameters struct {

	// The AWS access key ID for signing programmatic requests.
	// The AWS access key ID for signing programmatic requests.
	// +kubebuilder:validation:Optional
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	// A unique identifier that is used by third parties when assuming roles in their customers' accounts, aka cross-account role access.
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Optional identifier for the assumed role session.
	// Optional identifier for the assumed role session.
	// +kubebuilder:validation:Optional
	RoleSessionName *string `json:"roleSessionName,omitempty" tf:"role_session_name,omitempty"`

	// The Amazon Resource Name (ARN) of the role to assume.
	// The Amazon Resource Name (ARN) of the role to assume.
	// +kubebuilder:validation:Optional
	RoleToAssume *string `json:"roleToAssume,omitempty" tf:"role_to_assume,omitempty"`

	// The AWS secret access key for signing programmatic requests.
	// The AWS secret access key for signing programmatic requests.
	// +kubebuilder:validation:Optional
	SecretAccessKeySecretRef *v1.SecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The AWS session token for signing programmatic requests.
	// The AWS session token for signing programmatic requests.
	// +kubebuilder:validation:Optional
	SessionTokenSecretRef *v1.SecretKeySelector `json:"sessionTokenSecretRef,omitempty" tf:"-"`

	// Enable this to attempt getting credentials with OIDC token from Azure Devops.
	// Enable this to attempt getting credentials with OIDC token from Azure Devops.
	// +kubebuilder:validation:Optional
	UseOidc *bool `json:"useOidc,omitempty" tf:"use_oidc,omitempty"`
}

// ServiceendpointAwsSpec defines the desired state of ServiceendpointAws
type ServiceendpointAwsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServiceendpointAwsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceendpointAwsInitParameters `json:"initProvider,omitempty"`
}

// ServiceendpointAwsStatus defines the observed state of ServiceendpointAws.
type ServiceendpointAwsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceendpointAwsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceendpointAws is the Schema for the ServiceendpointAwss API. Manages a AWS service endpoint within Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type ServiceendpointAws struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	Spec   ServiceendpointAwsSpec   `json:"spec"`
	Status ServiceendpointAwsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceendpointAwsList contains a list of ServiceendpointAwss
type ServiceendpointAwsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceendpointAws `json:"items"`
}

// Repository type metadata.
var (
	ServiceendpointAws_Kind             = "ServiceendpointAws"
	ServiceendpointAws_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceendpointAws_Kind}.String()
	ServiceendpointAws_KindAPIVersion   = ServiceendpointAws_Kind + "." + CRDGroupVersion.String()
	ServiceendpointAws_GroupVersionKind = CRDGroupVersion.WithKind(ServiceendpointAws_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceendpointAws{}, &ServiceendpointAwsList{})
}
