// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ServiceendpointNexusInitParameters struct {

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The Service Endpoint password to authenticate at the Nexus IQ Instance.
	// The Nexus password.
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The ID of the project. Changing this forces a new Service Connection Nexus to be created.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// The name of the service endpoint. Changing this forces a new Service Connection Nexus to be created.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The Service Endpoint url.
	// Url for the Nexus Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Service Endpoint username to authenticate at the Nexus IQ Instance.
	// The Nexus user name.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ServiceendpointNexusObservation struct {

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project. Changing this forces a new Service Connection Nexus to be created.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The name of the service endpoint. Changing this forces a new Service Connection Nexus to be created.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The Service Endpoint url.
	// Url for the Nexus Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Service Endpoint username to authenticate at the Nexus IQ Instance.
	// The Nexus user name.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ServiceendpointNexusParameters struct {

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The Service Endpoint password to authenticate at the Nexus IQ Instance.
	// The Nexus password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The ID of the project. Changing this forces a new Service Connection Nexus to be created.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// The name of the service endpoint. Changing this forces a new Service Connection Nexus to be created.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The Service Endpoint url.
	// Url for the Nexus Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// The Service Endpoint username to authenticate at the Nexus IQ Instance.
	// The Nexus user name.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// ServiceendpointNexusSpec defines the desired state of ServiceendpointNexus
type ServiceendpointNexusSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServiceendpointNexusParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceendpointNexusInitParameters `json:"initProvider,omitempty"`
}

// ServiceendpointNexusStatus defines the observed state of ServiceendpointNexus.
type ServiceendpointNexusStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceendpointNexusObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceendpointNexus is the Schema for the ServiceendpointNexuss API. Manages a Service Connection for Nexus IQ.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type ServiceendpointNexus struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   ServiceendpointNexusSpec   `json:"spec"`
	Status ServiceendpointNexusStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceendpointNexusList contains a list of ServiceendpointNexuss
type ServiceendpointNexusList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceendpointNexus `json:"items"`
}

// Repository type metadata.
var (
	ServiceendpointNexus_Kind             = "ServiceendpointNexus"
	ServiceendpointNexus_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceendpointNexus_Kind}.String()
	ServiceendpointNexus_KindAPIVersion   = ServiceendpointNexus_Kind + "." + CRDGroupVersion.String()
	ServiceendpointNexus_GroupVersionKind = CRDGroupVersion.WithKind(ServiceendpointNexus_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceendpointNexus{}, &ServiceendpointNexusList{})
}
