// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ServiceendpointDynamicsLifecycleServicesInitParameters struct {

	// The URL of the Authentication Endpoint.
	AuthorizationEndpoint *string `json:"authorizationEndpoint,omitempty" tf:"authorization_endpoint,omitempty"`

	// The client ID for a native application registration in Azure Active Directory with API permissions for Dynamics Lifecycle Services.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The URL of the Lifecycle Services API Endpoint.
	LifecycleServicesAPIEndpoint *string `json:"lifecycleServicesApiEndpoint,omitempty" tf:"lifecycle_services_api_endpoint,omitempty"`

	// The Password for the Azure Active Directory account.
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The E-mail address of user with sufficient permissions to interact with LCS asset library and environments.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ServiceendpointDynamicsLifecycleServicesObservation struct {

	// +mapType=granular
	Authorization map[string]*string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// The URL of the Authentication Endpoint.
	AuthorizationEndpoint *string `json:"authorizationEndpoint,omitempty" tf:"authorization_endpoint,omitempty"`

	// The client ID for a native application registration in Azure Active Directory with API permissions for Dynamics Lifecycle Services.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The Service Endpoint description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the service endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The URL of the Lifecycle Services API Endpoint.
	LifecycleServicesAPIEndpoint *string `json:"lifecycleServicesApiEndpoint,omitempty" tf:"lifecycle_services_api_endpoint,omitempty"`

	// The ID of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The Service Endpoint name.
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The E-mail address of user with sufficient permissions to interact with LCS asset library and environments.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ServiceendpointDynamicsLifecycleServicesParameters struct {

	// The URL of the Authentication Endpoint.
	// +kubebuilder:validation:Optional
	AuthorizationEndpoint *string `json:"authorizationEndpoint,omitempty" tf:"authorization_endpoint,omitempty"`

	// The client ID for a native application registration in Azure Active Directory with API permissions for Dynamics Lifecycle Services.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The Service Endpoint description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The URL of the Lifecycle Services API Endpoint.
	// +kubebuilder:validation:Optional
	LifecycleServicesAPIEndpoint *string `json:"lifecycleServicesApiEndpoint,omitempty" tf:"lifecycle_services_api_endpoint,omitempty"`

	// The Password for the Azure Active Directory account.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// The ID of the project.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-azuredevops/apis/cluster/project/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// The Service Endpoint name.
	// +kubebuilder:validation:Optional
	ServiceEndpointName *string `json:"serviceEndpointName,omitempty" tf:"service_endpoint_name,omitempty"`

	// The E-mail address of user with sufficient permissions to interact with LCS asset library and environments.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// ServiceendpointDynamicsLifecycleServicesSpec defines the desired state of ServiceendpointDynamicsLifecycleServices
type ServiceendpointDynamicsLifecycleServicesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServiceendpointDynamicsLifecycleServicesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceendpointDynamicsLifecycleServicesInitParameters `json:"initProvider,omitempty"`
}

// ServiceendpointDynamicsLifecycleServicesStatus defines the observed state of ServiceendpointDynamicsLifecycleServices.
type ServiceendpointDynamicsLifecycleServicesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceendpointDynamicsLifecycleServicesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceendpointDynamicsLifecycleServices is the Schema for the ServiceendpointDynamicsLifecycleServicess API. Manages a Dynamics Lifecycle Services service endpoint within Azure DevOps organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azuredevops}
type ServiceendpointDynamicsLifecycleServices struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authorizationEndpoint) || (has(self.initProvider) && has(self.initProvider.authorizationEndpoint))",message="spec.forProvider.authorizationEndpoint is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.lifecycleServicesApiEndpoint) || (has(self.initProvider) && has(self.initProvider.lifecycleServicesApiEndpoint))",message="spec.forProvider.lifecycleServicesApiEndpoint is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceEndpointName) || (has(self.initProvider) && has(self.initProvider.serviceEndpointName))",message="spec.forProvider.serviceEndpointName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   ServiceendpointDynamicsLifecycleServicesSpec   `json:"spec"`
	Status ServiceendpointDynamicsLifecycleServicesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceendpointDynamicsLifecycleServicesList contains a list of ServiceendpointDynamicsLifecycleServicess
type ServiceendpointDynamicsLifecycleServicesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceendpointDynamicsLifecycleServices `json:"items"`
}

// Repository type metadata.
var (
	ServiceendpointDynamicsLifecycleServices_Kind             = "ServiceendpointDynamicsLifecycleServices"
	ServiceendpointDynamicsLifecycleServices_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceendpointDynamicsLifecycleServices_Kind}.String()
	ServiceendpointDynamicsLifecycleServices_KindAPIVersion   = ServiceendpointDynamicsLifecycleServices_Kind + "." + CRDGroupVersion.String()
	ServiceendpointDynamicsLifecycleServices_GroupVersionKind = CRDGroupVersion.WithKind(ServiceendpointDynamicsLifecycleServices_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceendpointDynamicsLifecycleServices{}, &ServiceendpointDynamicsLifecycleServicesList{})
}
