apiVersion: repos.azuredevops.crossplane.io/v1alpha1
kind: CheckBusinessHours
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/checkbusinesshours
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: Managed by Terraform
    endTime: "15:30"
    monday: true
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    startTime: "07:00"
    targetResourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    targetResourceType: endpoint
    timeZone: UTC
    timeout: 1440
    tuesday: true

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/checkbusinesshours
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Project

---

apiVersion: serviceendpoint.azuredevops.crossplane.io/v1alpha1
kind: ServiceendpointGeneric
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/checkbusinesshours
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Managed by Terraform
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverUrl: https://some-server.example.com
    serviceEndpointName: Example Generic
    username: username
