apiVersion: repos.azuredevops.crossplane.io/v1alpha1
kind: GitRepositoryFile
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/gitrepositoryfile
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    branch: refs/heads/master
    commitMessage: First commit
    content: '**/*.tfstate'
    file: .gitignore
    overwriteOnCreate: false
    repositoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: repos.azuredevops.crossplane.io/v1alpha1
kind: GitRepository
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/gitrepositoryfile
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Git Repository
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.azuredevops.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: repos/v1alpha1/gitrepositoryfile
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
